### ISSUE TITLE
Case for particle scene path in player script needs uppercased

### ISSUE THREAD

**Issue by RancidMilkGames** [alpapaydin/Godot4-3D-Smooth-Destructible-Terrain#1]
Itty bitty thing. line 52 in `player.gd` should be `var particleScene := preload("res://Scenes/Player/mining_particles.tscn")`.
Currently "player" in the path isn't capitalized. I think Windows might also ignore this(?), but Linux users do have to fix it for it to work.

**Comment by alpapaydin** [comment]
Thanks, fixed now.

**Comment by RancidMilkGames** [comment]
Awesome! I was thinking about going the normal route of a pull request, but figured it was the tiniest thing in the world and some developers are weird about people making small contributions, especially non meaningful ones. Cool project by the way!

**Comment by alpapaydin** [comment]
Thank you so much! You are always welcome to contribute, also with new ideas.

**Comment by RancidMilkGames** [comment]
Whooo!!! First contribution! I should have sat down and figured out how to do that a little while ago, as I know I've run into a few other things I thought might be of benefit, but do now know the process so you're very likely to see me here and there. I also appreciate the positivity, thank you!!

**Comment by RancidMilkGames** [comment]
Haha, if my last message doesn't make sense, I forgot I even sent this message because it was a small capitalization fix. I made my first attempt at contributing to the Godot docs and just saw the word Godot and thought that it had been accepted.
